# Generated by Django 5.2.12 on 2026-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
                'db_table': 'staff',
            },
        ),
    ]
