# Generated by Django 5.2.12 on 2026-03-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.basemodel')),
                ('full_name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('about', models.CharField(max_length=255)),
                ('professions', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'db_table': 'authors',
            },
            bases=('shared.basemodel',),
        ),
        migrations.CreateModel(
            name='PopularPosts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.basemodel')),
                ('title', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
            ],
            options={
                'verbose_name': 'popular post',
                'verbose_name_plural': 'popular posts',
                'db_table': 'popular_posts',
            },
            bases=('shared.basemodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.basemodel')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tags',
            },
            bases=('shared.basemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.basemodel')),
                ('title', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
            bases=('shared.basemodel',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.basemodel')),
                ('title', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('long_description', models.TextField()),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20)),
                ('authors', models.ManyToManyField(related_name='blogs', to='blog.author')),
                ('categories', models.ManyToManyField(related_name='blogs', to='blog.category')),
                ('tags', models.ManyToManyField(related_name='blogs', to='blog.tag')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'db_table': 'blogs',
            },
            bases=('shared.basemodel',),
        ),
    ]
