# Generated by Django 5.2.12 on 2026-03-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='popularposts',
            options={'verbose_name': 'Popular post', 'verbose_name_plural': 'Popular posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.CharField(max_length=255, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='author',
            name='professions',
            field=models.CharField(max_length=128, verbose_name='Professions'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(related_name='blogs', to='blog.author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blog.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='long_description',
            field=models.TextField(verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blog.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blog.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='popularposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='popularposts',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='popularposts',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
